language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - cd ./template
  - npm install
  - npm test

env:
  global:
    - CODECOV_TOKEN="019eb49e-8711-4953-aa41-90c572bbcdb1"
